### ISSUE TITLE
Dimensions of random_point and random_tangent for Euclidean manifold with multiple dimensions is inconsistent

### ISSUE THREAD

**Issue by const-ae** [JuliaManifolds/Manopt.jl#109]
The constructor for the Euclidean manifold accepts varargs for the size. For example 
```julia
E = Euclidean(3, 5)
```
generates a space of `3 x 5` matrices.

Accordingly, `p = random_point(E)` returns a `3 x 5` array. However, `random_point(E, :Gaussian, 3)` and `random_tangent(E, p)` return vectors with 15 elements. This is because these functions internally use `manifold_dimension(M)` instead of `representation_size(M)`.

If you want, I could draft a PR so that all function for example use `representation_size` internally.

**Comment by mateuszbaran** [comment]
Yes, I think returned points and tangent vectors should definitely return arrays with the size consistent with `representation_size`. A PR would be appreciated :+1: .
