### ISSUE TITLE
Notation related to ξ in CG descent

### ISSUE THREAD

**Issue by mahaa2** [JuliaManifolds/Manopt.jl#148]
In this link -  https://manoptjl.org/stable/solvers/conjugate_gradient_descent/ -
which are methods related to conjugate gradient on the manifolds I didn't follow the notation related to ξ.
what is the role of ξ ? 

Thanks.

**Comment by kellertuer** [comment]
ξ (k for the last, k+1 for the current iterate ones) refers to the gradient.

**Comment by kellertuer** [comment]
I updated it both in the Options

https://manoptjl.org/previews/PR149/solvers/conjugate_gradient_descent/#Manopt.ConjugateGradientDescentOptions

as well as in every single coefficient rule, e.g. 

https://manoptjl.org/previews/PR149/solvers/conjugate_gradient_descent/#Manopt.ConjugateDescentCoefficient

Does this help? If so I can resolve this by merging #149 :)

**Comment by mahaa2** [comment]
Hi,

One last question is that the formula for the search direction δ_k has β_k which can be chosen by via different methods but β_k involves ξ_k and ξ_{k + 1}, should it be ξ_{k - 1} and ξ_k. Otherwise looks awesome

**Comment by kellertuer** [comment]
Thats more of a philosophical question, namely whether you are at iteration k and compute the  δ_k has β_k _from the last_ iteration k-1 for _for_ the next iteration k+1.

**Comment by mahaa2** [comment]
Thanks !
