### ISSUE TITLE
"Onto" -> "to"

### ISSUE THREAD

**Issue by dojt** [JuliaManifolds/Manopt.jl#157]
https://github.com/JuliaManifolds/Manopt.jl/blob/46aea2dd0aa11ba8a1a209674ff91cbdc866e6ed/Readme.md?plain=1#L13

Onto (["onto" on Wikipedia](https://en.wikipedia.org/w/index.php?title=Onto)), in English, refers to the property of the mapping being surjective. No point minimizing them... 🙂

**Comment by kellertuer** [comment]
Could you quickly open that as a PR? That would fix it fast and you'll be a contributor :)
