### ISSUE TITLE
access semantic elements of the Options and Problem by symbolic indexing.

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manopt.jl#158]
Currently Manopt.jl has a lot of access functions to encapsulate a lot of semantic elements, especially of the Options but also of the Problem.

Instead (so as a braking change for the internal structure) we could move to a nicer form, namely dressing them by symbols.

Instead of
```julia
get_gradient(o)
```
to access where any option stores their gradient, we could use
```julia
o[:Gradient]
```
implementing a proper `get_index` for options and problems. These symbols should then be named the same as we use for debug and record.

Currently the following would be reasonable

* `:Iterate` for the current point in the options
* `:Gradient` for a current gradient
* `:Hessian` For a current second order information at an iterate
* `:Subgradient`

As well as for the problem

* `:Cost` to return the cost function
* `:Gradient` to return the gradient function
* `:CostGrad` to adress #139 and unify this in the framework as well.
* `:Manifold` to return the domain of optimisation
* `:Prox`, `:Proxes`, `:PrimalProx`, `:DualProx` for the different proximal maps
* `:Subgradient` to return the sub gradient function
* `:Hessian` to return the Hessian function.

**Comment by mateuszbaran** [comment]
`get_gradient(o)` looks to me more idiomatic for Julia, and implementing `o[:Gradient]` efficiently may be a bit of a headache. Are you sure about this?

**Comment by kellertuer** [comment]
I don'† completely know yet, I just felt that I might have too many of the get functions and the only difference would be that instead of

```
get_gradient(o::SomeOptions)
```

I would implement
```
get_index(o::SomeOptions,:Gradient)
```
?

**Comment by mateuszbaran** [comment]
No, you can't do `get_index(o::SomeOptions, :Gradient)`. You would have to implement `get_index(o::SomeOptions, s::Symbol)` and inside that method check whether `s` is `:Gradient`, `:Iterate` or something else.

**Comment by mateuszbaran** [comment]
I think the `get_` function interface is fine. You could also just remove `get_` from names of these functions if you don't like it :slightly_smiling_face: .

**Comment by kellertuer** [comment]
Ah right, I would have to dispatch on Value there, that's right.
I was just feeling in code it might look nicer to have accessors like `o[:Gradienbt]` instead of `get_gradient(o)`

**Comment by kellertuer** [comment]
Hm, probably correct, it does not matter whether one has to know magic symbols or magic function names, with the difference that the magic functions names have autocomplete and docs. So lets stick with the names, the idea here is not good.
