### ISSUE TITLE
Where does the logarithmic map and exponential map come from? 

### ISSUE THREAD

**Issue by hzg0601** [JuliaManifolds/Manopt.jl#160]
would you please list some references that give the detail about where the logarithmic map and exponential map come from?

**Comment by kellertuer** [comment]
Good morning.

For the general theory I would recommend for example the book “Riemannian Geometry” by Manfredo P. do Carmo, or with respect to optimisation “Optimisation Algorithms” by Absil, Mahony & Sepulchre ( http://www.inma.ucl.ac.be/~absil/amsbook/ ) or “An introduction to optimization on smooth manifolds” by Nicolas Boumal (https://www.nicolasboumal.net/book/index.html).
You are right I could add the third one, which is relatively new, to the Section on https://manoptjl.org/stable/#Literature as well.

If you have a specific manifold in mind, and it is implemented in Manifolds.jl check out the specific pages at https://juliamanifolds.github.io/Manifolds.jl/latest/ to see the actual formulae used and references where they are from.

**Comment by hzg0601** [comment]
> Good morning.
> 
> For the general theory I would recommend for example the book “Riemannian Geometry” by Manfredo P. do Carmo, or with respect to optimisation “Optimisation Algorithms” by Absil, Mahony & Sepulchre ( http://www.inma.ucl.ac.be/~absil/amsbook/ ) or “An introduction to optimization on smooth manifolds” by Nicolas Boumal (https://www.nicolasboumal.net/book/index.html). You are right I could add the third one, which is relatively new, to the Section on https://manoptjl.org/stable/#Literature as well.
> 
> If you have a specific manifold in mind, and it is implemented in Manifolds.jl check out the specific pages at https://juliamanifolds.github.io/Manifolds.jl/latest/ to see the actual formulae used and references where they are from.

Thank you so much for the invaluable replay, which is particularly helpful for me. I do have a special manifold in mind--hyperbolic. I particularly wonder where the `log` and `exp` come from in Mainfolds.jl/src/manifold/Hyperbolic.jl. Actually, I have read many papers on hyperbolic geometry, and almost none of them explicitly list the references where their exp and log map come from. I have read many books about hyperbolic geometry too, and unfortunately, none of them concretely write down the particular formula of these maps. It bothers me for a long time. It will be highly appreciated if you list some references on where the formulas of these maps come from. Again, thank you for your valuable reply.

**Comment by kellertuer** [comment]
Well thee formulae of these maps _are_ written down concretely for example https://juliamanifolds.github.io/Manifolds.jl/latest/manifolds/hyperbolic.html#Base.exp-Tuple{Hyperbolic,%20Vararg{Any}} - so they are written down quite often, the main thing you have to do is to compute the second order for acceleration free curves in Minkowski space.

**Comment by hzg0601** [comment]
Thanks again for the patient reply! But I believe these formulas must be written down according to some certain book or paper, and what I most want to know is the title of the book or paper. I read these formulas for several times, however, most of them are written down according to a book written by a professor named Ungar, who develops a theory called gyrovector space which is not very convincing for me. So I wonder if there are some other books that concretely written down these maps.

**Comment by kellertuer** [comment]
Most textbooks cover that, see for example John M. Lee, “Introduction to curvature”, Springer, 1997, Chapter 5, “Reiammnian Geodesics”, Proposition 5.14 (even in all 3 representations) – and of course Chapter 5 in general for the theory (but as mentioned above you can also read do Carmo for that).

I am not sure what you mean with “most of them”, but I have not heard of Ungar nor of gyro vector space (but I am also from a different field it seems).

**Comment by hzg0601** [comment]
Thans a lot !!!
