### ISSUE TITLE
invalid ssl certificate for tutorial link

### ISSUE THREAD

**Issue by tpapp** [JuliaManifolds/Manopt.jl#17]
The link https://manoptjl.org/stable/tutorials/MeanAndMedian/ in the README leads to a site that has an invalid SSL certificate.

**Comment by kellertuer** [comment]
Thanks for notifying, it ran out today. I will fix this before lunch.

**Comment by kellertuer** [comment]
Interesting: This link works https://www.manoptjl.org/stable/tutorials/MeanAndMedian/ – and I still have to figure out why one domain works and the other does not (yet, again?) – the www-domain has an updated certificate for the next year.

**Comment by kellertuer** [comment]
Somehow Github updated a certificate for the www prefix but not for the other one. I updated the link in the readme accordingly.
