### ISSUE TITLE
ManoptBase.jl (or ideas for improving the basic interfaces for Manopt.jl)

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manopt.jl#172]
Maybe it would be a good idea to introduce a generic interface for algorithms – ManoptBase.jl

I am not yet 100% sure, but something like the Problem and the options and the decorator pattern for the options would be nice to have in a generic form; maybe also the debug/record/stepsize abstract ideas.
One could use this to rethink a few design decisions (most of them were made when I learned Julia). On the other hand, with the sub solvers now being covered, I think the main interface / design ideas are available, so Manopt.jl is mature enough to think about this step

Then Manopt.jl would be more of a “Library of Optimisation Algorithms” (similar to Manifolds.jl).

This issue is meant to keep track of this idea and collect necessary things to think / redesign for that.

# Ideas / Things to change for Manopt 0.4

* rename `Problem` to `AbstractProblem` or maybe even better `RiemannianProblem`
* rename `Options` to `AbstractOptions` or maybe even better `SolverOptions`
* use the new Decorator ideas https://juliamanifolds.github.io/ManifoldsBase.jl/stable/decorator.html for the Options and the stepsize. Maybe we could even make said Decorator pattern its own package before?
* the main function should be called `solve!` not `solve`
* it might be easier (and more flexible) to store the evaluation type with the function(s) not the problem. I thought  about this already, that it might be nice to combine in-place and allocating functions. So the default would still be the allocation type, but the mutating one is a type `<: MutatingXFunction`, so a functor. This way quite a few `get_gradient` and such functions would be much easier, I think (less boiler plate code).
* the functions and differentials could be exported to ManoptExamples.jl
* remove deprecated constructors.
* reorganise code: Move Options to their solvers.
* reorganise Docs similarly

**Comment by mateuszbaran** [comment]
I think currently there are no packages that would depend on ManoptBase.jl instead of Manopt.jl?

**Comment by kellertuer** [comment]
My idea would be that maybe something like #173 ManoptExamples would, but sure if that would need the whole Manopt.jl then there is maybe not so much need for an extra base package here.
The I might still collect redesign things that are good for the “lower layer” for Manopt.jl
