### ISSUE TITLE
Differentials and adjoint differentials in ManifoldDiff.jl

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#177]
Since we are thinking about a breaking release for Manopt.jl, there are a few points that we could discuss. First, some time ago I've copied and improved a bit differentials and adjoint differentials to ManifoldDiff.jl. I think this duplication could be removed for 0.4?

**Comment by mateuszbaran** [comment]
We haven't registered ManifoldDiff yet but I will do that this week.

**Comment by kellertuer** [comment]
But then we also have to check which functions are available and which are not; I think you did not take over gradients/proxes?

**Comment by kellertuer** [comment]
Could we maybe switch one thing and define

```
    AbstractDiffBackend,
    NoneDiffBackend,
    default_differential_backend,
    set_default_differential_backend!
```

in ManifoldDiff – and load them in Manifolds (instead of the other way around)? Then ManifoldDiff would not have to depend on Manifolds.jl and I could easily use it here, that would be great :)

**Comment by mateuszbaran** [comment]
So you want to make Manifolds.jl depend on ManifoldDiff.jl? That would likely work. I will think about it.

**Comment by kellertuer** [comment]
Yes, for the following reason. These abstract diff backends fit quite well into ManifoldDiff (they could also be put into ManifoldsBase alternatively) and `Manifolds.jl` adds to these anyways. It might also make it easier in the future to move things from `Manifolds.jl` “up to” ManifoldDiff.jl

And sure, if you feel it fits better those 4 elements could also go into `ManifoldsBase.jl` – they are surely generic enough. Do what you prefer.
