### ISSUE TITLE
`random_point` and `random_tangent`

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#178]
We now have `rand` methods in Manifolds.jl so most (if not all) uses of `random_point` and `random_tangent` can be replaced by `rand` for more consistency. Eventually it would be nice to support custom distributions in Manopt.jl but that's something that needs to be improved over what we currently have in Manifolds.jl.

**Comment by kellertuer** [comment]
Are you sure? There was something that kept me from moving over to rand, I fear. but I can try in one of the next steps again, sure.

**Comment by mateuszbaran** [comment]
All I can see is that random_tangent has Rician distribution on tangents but we can add that as a keyword argument to `rand` in Manifolds.jl. Let me know if there is any other issue.

**Comment by kellertuer** [comment]
For SPDs I think it has that also for points. That is what I would have to check. But sure, we can include this breaking change for 0.4 as well.
