### ISSUE TITLE
Line searches

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#181]
I was investigating why Armijo linesearch doesn't take injectivity radius as a parameter and I've found this: https://ins.uni-bonn.de/media/public/publication-media/RBFGS.pdf?pk=14 . I still don't know why it doesn't but this paper looks relevant.

**Comment by kellertuer** [comment]
Hm, can you be a little bit more precise on what the message there is and what this looks relevant for? The current Armijo line search is from Absil, Mahony, Sepulchre, Algorithm 1 in Chapter 4 (p. 63), if I remember correctly, with the small addition that one can provide a function to compute the step size to start with, based on an idea from the paper by Vandereycken ( https://arxiv.org/abs/1209.3834 ) where he has Alg. 5 to do such an initial guess.

**Comment by mateuszbaran** [comment]
Thanks for the reference, I looked at it a bit more closely and I think I was just confused.
