### ISSUE TITLE
Add simplex size termination condition to Nelder-Mead

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#183]
Something like in here: https://webpages.uidaho.edu/~fuchang/res/ANMS.pdf .

**Comment by kellertuer** [comment]
If you just implement a stopping criterion, this should be doable without getting in conflict with the preparations for 0.4 – because I might only write a few new functions for stopping criteria (something line `indicates_convergence` but not change their general format.
