### ISSUE TITLE
Add in-place variant of particle swarm optimization

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#186]
(as in the title)

**Comment by kellertuer** [comment]
Can you be a little more precise? The “swarm” is changed place I hope – the minimiser as well? Or do I see/remember that wrongly?

If you just change the solver part, that should even be fine compared to the rework.

**Comment by mateuszbaran** [comment]
No, the swarm isn't changed in place -- new positions are calculated using non-mutating functions entirely. In an in-place variant population would be modified in-place.

**Comment by kellertuer** [comment]
Oh then I had that wrongly in mind. Feel free to add/modify that.
