### ISSUE TITLE
vector_transport_to function in the grassmann manifolds  doesn't work unless using it with ProjectionTransport()  

### ISSUE THREAD

**Issue by Watayo** [JuliaManifolds/Manopt.jl#201]
Hi, I want to use CG-method in grassmann manifolds. but it cannot work, because of the vector_transport_to function of grassmann.
```
M = Grassmann(2, 2, ℂ)
p = rand(M)
X = rand(M; vector_at=p)
q = rand(M)
vector_transport_to(M, p, X, q)
```
error is below.
```
ERROR: MethodError: parallel_transport_to!(::AbstractManifold, ::Matrix{ComplexF64}, ::Matrix{ComplexF64}, ::Matrix{ComplexF64}, ::Matrix{ComplexF64}) is ambiguous. Candidates:
```
this called in  CG-methods (& the others) expects the parallel_transport_to!() for ::AbstractManifold or using it with ProjectionTransport()

**Comment by kellertuer** [comment]
Oh, I have to check for that.

Usually, the have the `default_vector_transport_method` (see https://juliamanifolds.github.io/ManifoldsBase.jl/stable/vector_transports.html#ManifoldsBase.default_vector_transport_method-Tuple{AbstractManifold}) that was introduced exactly for this case to provide a default that “just works”.

So reasons here could be
a) We missed to define that default for Grassmann (since if it is not defined it falls back to `ParallelTransport()`
b) I missed to replace `ParallelTransport()` somewhere in CG with the above-mentioned default function.

Can you maybe give me a little more of the Error stack?

**Comment by Watayo** [comment]
> It looks like this call already starts with the vector_transport_to 
Yes. this starts from `vector_transport_to`
Sorry I have tried CG-method in my project, but I'm caught in a new error just before now :-(
```
ERROR: LoadError: InexactError: Float64(-11.468177209250065 - 1.1988493587897888im)
Stacktrace:
  [1] Real
    @ ./complex.jl:44 [inlined]
  [2] convert(#unused#::Type{Float64}, x::ComplexF64)
    @ Base ./number.jl:7
  [3] setproperty!(x::Manopt.ConjugateGradientDescentState{Matrix{ComplexF64}, Matrix{ComplexF64}, Manopt.ConjugateDescentCoefficient, Manopt.ArmijoLinesearch{ManifoldsBase.PolarRetraction, typeof(Manopt.armijo_initial_guess)}, Manopt.StopWhenAny{Tuple{Manopt.StopAfterIteration, Manopt.StopWhenGradientNormLess}}, ManifoldsBase.PolarRetraction, ManifoldsBase.DifferentiatedRetractionVectorTransport{ManifoldsBase.PolarRetraction}}, f::Symbol, v::ComplexF64)
    @ Base ./Base.jl:39
  [4] step_solver!(amp::Manopt.DefaultManoptProblem{Manifolds.Stiefel{4, 4, ℂ}, Manopt.ManifoldGradientObjective{Manopt.AllocatingEvaluation, Main.Mera.var"#F#15"{Matrix{ComplexF64}}, Main.Mera.var"#gradF#16"{Matrix{ComplexF64}}}}, cgs::Manopt.ConjugateGradientDescentState{Matrix{ComplexF64}, Matrix{ComplexF64}, Manopt.ConjugateDescentCoefficient, Manopt.ArmijoLinesearch{ManifoldsBase.PolarRetraction, typeof(Manopt.armijo_initial_guess)}, Manopt.StopWhenAny{Tuple{Manopt.StopAfterIteration, Manopt.StopWhenGradientNormLess}}, ManifoldsBase.PolarRetraction, ManifoldsBase.DifferentiatedRetractionVectorTransport{ManifoldsBase.PolarRetraction}}, i::Int64)
    @ Manopt ~/.julia/packages/Manopt/XF5vn/src/solvers/conjugate_gradient_descent.jl:123
  [5] solve!(p::Manopt.DefaultManoptProblem{Manifolds.Stiefel{4, 4, ℂ}, Manopt.ManifoldGradientObjective{Manopt.AllocatingEvaluation, Main.Mera.var"#F#15"{Matrix{ComplexF64}}, Main.Mera.var"#gradF#16"{Matrix{ComplexF64}}}}, s::Manopt.ConjugateGradientDescentState{Matrix{ComplexF64}, Matrix{ComplexF64}, Manopt.ConjugateDescentCoefficient, Manopt.ArmijoLinesearch{ManifoldsBase.PolarRetraction, typeof(Manopt.armijo_initial_guess)}, Manopt.StopWhenAny{Tuple{Manopt.StopAfterIteration, Manopt.StopWhenGradientNormLess}}, ManifoldsBase.PolarRetraction, ManifoldsBase.DifferentiatedRetractionVectorTransport{ManifoldsBase.PolarRetraction}})
    @ Manopt ~/.julia/packages/Manopt/XF5vn/src/solvers/solver.jl:103
  [6] conjugate_gradient_descent!(M::Manifolds.Stiefel{4, 4, ℂ}, f::Main.Mera.var"#F#15"{Matrix{ComplexF64}}, grad_f::Main.Mera.var"#gradF#16"{Matrix{ComplexF64}}, p::Matrix{ComplexF64}; coefficient::Manopt.ConjugateDescentCoefficient, evaluation::Manopt.AllocatingEvaluation, stepsize::Manopt.ArmijoLinesearch{ManifoldsBase.PolarRetraction, typeof(Manopt.armijo_initial_guess)}, retraction_method::ManifoldsBase.PolarRetraction, stopping_criterion::Manopt.StopWhenAny{Tuple{Manopt.StopAfterIteration, Manopt.StopWhenGradientNormLess}}, vector_transport_method::ManifoldsBase.DifferentiatedRetractionVectorTransport{ManifoldsBase.PolarRetraction}, kwargs::Base.Pairs{Symbol, Union{}, Tuple{}, NamedTuple{(), Tuple{}}})
    @ Manopt ~/.julia/packages/Manopt/XF5vn/src/solvers/conjugate_gradient_descent.jl:109
  [7] #conjugate_gradient_descent#327
    @ ~/.julia/packages/Manopt/XF5vn/src/solvers/conjugate_gradient_descent.jl:59 [inlined]
```

**Comment by Watayo** [comment]
It was working yesterday... I haven't been able to track when it changed yet.

**Comment by kellertuer** [comment]
Before checking the other one, this one seems to be that you try to store a complex number in an float (that is what the inexact error tells you, that the complex number can not “just” be turned into a Float without being inexact) - and ah I see, beta is still a float, I should allow it to be a complex number as well. Will come soon :)

**Comment by Watayo** [comment]
> The only think I have to check is how to handle the case, that Grassmann has two representations (The Stiefel one and the projection matrix one), but only a vector transport for the first I think.

I expect Stiefel representations for now

**Comment by mateuszbaran** [comment]
> Sorry I have tried CG-method in my project, but I'm caught in a new error just before now :-(

This is again the case of `inner` returning a complex number, `ConjugateDescentCoefficient` should likely return the `real` part of the quotient of inner products (in this line: `return inner(M, cgs.p, cgs.X, cgs.X) / inner(M, p_old, -cgs.δ, X_old)`)

**Comment by kellertuer** [comment]
> > The only think I have to check is how to handle the case, that Grassmann has two representations (The Stiefel one and the projection matrix one), but only a vector transport for the first I think.
> 
> I expect Stiefel representations for now

Yes, I assumed so, however, there is a design-question: How should one be able to specify different default vector transports for different representations (maybe we have a manifold where representation A has parallel_transport, the other does not). I will think about that.

**Comment by Watayo** [comment]
> I should allow it to be a complex number as well. Will come soon :)

Yes it is . thank you for supports!

**Comment by mateuszbaran** [comment]
> > > Sorry I have tried CG-method in my project, but I'm caught in a new error just before now :-(
> > 
> > 
> > This is again the case of `inner` returning a complex number, `ConjugateDescentCoefficient` should likely return the `real` part of the quotient of inner products (in this line: `return inner(M, cgs.p, cgs.X, cgs.X) / inner(M, p_old, -cgs.δ, X_old)`)
> 
> I was not so sure whether those should be real – or we should have a more general beta – since it is basically a projection onto a vervain direction, which on a complex tangent space might include complex β or not? For sure a real would fix it but exclude certain directions I fear.

If this can indeed be complex then we should check if there doesn't need to be a conjugation somewhere?

**Comment by Watayo** [comment]
> How should one be able to specify different default vector transports for different representations 

oh this is confusing problem.
As the one solution, how about  fixing that it should be able to specify the representation options in solver? (but this is naive)
e.g. 
`conjugate_gradient_descent(M, F, gradF, x; representation="Stiefel")`

**Comment by kellertuer** [comment]
No CG is not the problem here - and passing Strings is very “Python-like”. CG works fine for both, also all internal methods do, just that

`default_vector_transport_method(M)`. would always return the same default independent of the representation, while there there might be a good reason to return different ones. And yes that is a different issue ;)

You can fix this (by the way) temporarily in your code by

```
using ManifoldsBase
import ManifoldsBase: default_vector_transport_method
default_vector_transport_method(::Grassmann) ProjectionTransport()
```

**Comment by kellertuer** [comment]
And concerning the beta, the only question is: Do we make the inners real or do we make the beta complex ;) ? Then this is also an easy fix.

By the way – thanks for trying this out and your patience (since you are the first doing complex manifolds in Manopt).

**Comment by Watayo** [comment]
> And concerning the beta, the only question is: Do we make the inners real or do we make the beta complex ;) ? Then this is also an easy fix.

There has been no change in the code since #199, correct? 
if so, I expect inners real. (Is it some numerical error that beta is now complex?)
and I'd like to try beta complex version.

**Comment by kellertuer** [comment]
> > And concerning the beta, the only question is: Do we make the inners real or do we make the beta complex ;) ? Then this is also an easy fix.
> 
> There has been no change in the code since #199, correct? if so, I expect inners real. (Is it some numerical error that beta is now complex?) and I'd like to try beta complex version.

That is what I just checked – and first: No there were no changes in the code you use since #199,
but that change was done with one distinction: If the `inner`s were “distance-related” e.g. in Armijo or within a cost function, `real(...)` was added. If not – then not, since (also for the `beta`) then it might be “projection-related” in the tangent space and then we are interested in the complex number.

If you check with https://en.wikipedia.org/wiki/Conjugate_gradient_method#Conjugate_gradient_method_for_complex_Hermitian_matrices

The beta (called alpha therein in the code) can be complex in the complex case) so I mainly have to allow for that and adapt the code – just need to find out how to set the type of beta correctly when constructing the state :)

**Comment by mateuszbaran** [comment]
> The beta (called alpha therein in the code) can be complex in the complex case) so I mainly have to allow for that and adapt the code – just need to find out how to set the type of beta correctly when constructing the state :)

I think you can re-use `allocation_promotion_function` we already have for this purpose.

**Comment by Watayo** [comment]
> If the inners were “distance-related” e.g. in Armijo or within a cost function, real(...) was added. If not – then not, since (also for the beta) then it might be “projection-related” in the tangent space and then we are interested in the complex number.

It's problem-dependent?
if so I will check my problem.

**Comment by Watayo** [comment]
In the first place is `real-inner = real(dot(x, y))` (see #197) correct in 
complex-space? 
We should use Hermite inner product??
And I expect complex-beta

**Comment by kellertuer** [comment]
What do you mean by “in the first place”? Which first pace? Where?

Sure a complex beta is coming soon, as I said.

**Comment by Watayo** [comment]
> What do you mean by “in the first place”? Which first pace? Where?
this is #199. I questioned the definition of real-inner in complex-manifold

**Comment by Watayo** [comment]
Sorry I have some mistake.

**Comment by kellertuer** [comment]
concerning the vector transport, the final fix might take a while, since we will first discuss the interface to distinguish different representations (cf. JuliaManifolds/ManifoldsBase.jl#144. Until then (besides the function definition fix above) you can also always pass the method down explicitly using `vector_transport_method=ProjectionTransport()` for now.
Sure the default is there to make it easier-to-use, but mentioning it explicitly is also always a possibility.

**Comment by kellertuer** [comment]
Just to mention for the second part (so you do not have to pass ProjectionTransport) we introduced

and now
https://github.com/JuliaManifolds/Manopt.jl/pull/208
and
https://github.com/JuliaManifolds/Manifolds.jl/pull/568

adapt the defaults accordingly and introduce a `ProjectionTransport()` default for the Grassmann in Stiefel-representation.
So then it should even work without explicitly passing the retraction method.
