### ISSUE TITLE
Rename `HeestenesStiefelCoefficient` to `HestenesStiefelCoefficient`

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#204]
It looks like a typo (two 'e' instead of one).

**Comment by kellertuer** [comment]
Yes that is a typo, the only question then would be – is that a breaking change? I think it is, though it is a bugfix?

**Comment by kellertuer** [comment]
That sounds like a good idea, maybe even mark it with a deprecated? Then we keep in mind to remove it on next release :)
