### ISSUE TITLE
Incorrect gradient change debugging

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#213]
This is the current code for debugging gradient change:
https://github.com/JuliaManifolds/Manopt.jl/blob/2d4a5a7575948204408e01bb19e1f88feec8a6d9/src/plans/debug.jl#L211
`distance` is not a valid operation on tangent vectors.

**Comment by kellertuer** [comment]
I already noticed this when working on #211 and it is resolved in there see https://github.com/JuliaManifolds/Manopt.jl/pull/211/files#diff-d8a6071071e9c63dc320bb2cd0fa05ea84f8743be3df3a4dd0234a9e0ca5eb4f line 252

**Comment by mateuszbaran** [comment]
Yes, thanks!
