### ISSUE TITLE
Convert storage-using stopping criteria to faster storage handling

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#214]
See the new storage from #212 . That's a bit nontrivial because currently these criteria don't get a point/gradient examples.

**Comment by mateuszbaran** [comment]
And also other things that use storage could start using the faster variant.

**Comment by kellertuer** [comment]
Debugs for example.

But it mainly would include to transfer them to using the point/vector storages instead of the dictionary, right? I will have to read about your new constructor once that is finished.

**Comment by mateuszbaran** [comment]
Yes, that's right. I'm not going to work on that in #212 (the old storage can still be used) but it would be a good thing to do in a later PR.

**Comment by kellertuer** [comment]
Good, thanks for the clarification, sure, as soon as the constructor for the new parts of the storage are in place we can move the other “storage-users” as well, mainly a few stopping criteria and debugs.

**Comment by kellertuer** [comment]
I think this is resolved in #212, since we introduced the new storage ways and a new (optional) manifold that can be specified.
