### ISSUE TITLE
Thoughts on improving state storage (even further)

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manopt.jl#220]
Recently there were two great improvement PRs on the state storage and quite a few discussions. I thought a bit about the status and how to even improve this further. I would like to summarise this here and look forward to how this can be improved even further.

# Motivation

the initial motivation comes from the fact that there are several “things” that are not always required, and if they are not required they maybe should not be stored to spare memory.
The easiest example is maybe the gradient descent algorithm, if the just fix

* a max number of iterations as a stopping criterion
* a constant stepsize

(not the best of algorithms, merely to illustrate something). Then the algorithm does not need to store the last iterate nor the last step. This would only be required if we check for the last change (e.g. as a stopping criterion) or store the last gradient to check for a gradient change.
Even the gradient evaluation does not need to be saved, only if the need it in more places then the `exp`.

So with this it would be great to have a “flexible storage” where several components can store stuff or request stuff to be stored if necessary.

# Current State: Decentralized
Currently there is the `StateStorageAction` which is storage attached to `Actions` that is e.g. stopping criteria, stepsize rules, debug output or record actions.

Usually these are currently mainly independent storages, though the initial design was to also have a common one that is passed to all them. The challenge here is the update, which currently might have negative side effect.

## Example
a debug printing the change and a stopping criterion using the change both require the last iterate. If they share a storage for that, one might update the storage before the other one uses the last iterate and hence print a change of 0 afterwards

## Possible Solution
We could “double” the storage which 
1. every current “update” would write into a “shadow storage”
2. one always _reads_ from the “front storage”
3. at the end of an iteration these two storages could be switched. This avoids the side effects mentioned, but is a little technical

## Advantage
One relatively large advantage that I see in this approach is, that anyone implementing a new solver does not have to think about these things, since they are decentralised

## Disandvantage
Getting the communication to work properly (see possible solution) is a bit technical I fear

# Possible other Solution
Instead of having individual storages we could do one central storage in all `AbstractManoptSolverState`s. That way the update would just happen at the end of a step, which might be a bit complicated considering that the decorators usually act _after_ a step is performed, but at least this would lead to a central place where the “update” mentioned above would be performed

On the other hand all actions mentioned above have the state in their functor, so accessing the central storage should not be a problem. 

## Challenge: Flexibility

One challenge in this approach might be flexibility, that is when generating the state, it might not be 100% known which actions (again thing stop/step/debug/record in the future maybe count) use the storage.

One way to adress this would be to use the functors of these actions at the start (iteration `I=0`) where each action could “report” the fields it needs. If they are present (in performant or nonperformant fields) all is fine, otherwise they are added – probably to the nonperformant dictionary area.
Still, when setting up the state one could allow a `storage=` field where the advanced user could set up all fields (even in point/vector storage) he anticipated the actions will use, then the “reporting” will just use the efficient ones that already exist.

In this approach we “automatically” get a centralised storage, that can still be flexible.
Even more – by default, the gradient descent would not require any of this storage, the quasi Newton could directly have a default for the last iterate int the `storage=` field.
Of course still `init_solver` would make sure the required fields exist (similar to the init steps in the actions), so if a “malicious” user would pass a storage without `last_iterate` field it would be reserved in the init step (well probably in the inefficient part, but well).

## Advantage
a centralised storage is easier to handle and probably easier to manage. Whether something is a field in the state or in the states storage is a bit of a discussion, but anything that is optional would be definetly in the storage, while anything that is a fixed parameter would be in the state (and for example easier to access by `DebugEntry` but one could also do a.`DebugStorageEntry` then)
The same decision of course holds anyways already for any action, whether something they store (e.g. initial time in DebugTime) is a local field or a storage entry).

## Disadvantage
Implementing new solvers is a bit more involved since one has to have the storage setup in every solver state (an initial reason for the decentralised stuff). 

# Summary

I am a bit in favour of an internal rework to the second idea, though that means we would add a `storage` field in each and every solver and remove it from the actions.
@mateuszbaran what do you think? This is of course nothing too urgent, but doing this right might be worth a bit of a reorganisation in the code.

I hope this (little longish) summary illustrates why the storage exists and might yield something that is efficient in the end :)

**Comment by mateuszbaran** [comment]
I think at this point I would just leave further work on storage for later -- any variant of further improvements requires quite a lot of work.

The most important point in my opinion is that we should allow for local storage in variables outside of `StorageStateAction`. This is still a step in the right direction and it would make later improvements to storage easier. It will also highlight what features of such storage are actually needed.

**Comment by kellertuer** [comment]
I think with the current storage and the cache, this should be fine for now.
