### ISSUE TITLE
Polyak's stepsize

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#224]
Example reference: https://web.stanford.edu/class/ee364b/lectures/subgrad_method_slides.pdf . This looks relatively simple :).

**Comment by kellertuer** [comment]
Sure looks nice and not so much to do, maybe for the gamma-rule, but that should be simple to what we do with the lambdas in CPPA, so one just has to fine a bit of time, which might for me only be in a week or two.

**Comment by mateuszbaran** [comment]
Decreasing step size works relatively well in my problem so for me it is more a nice-to-have thing for comparison than something I need, so it can wait.
