### ISSUE TITLE
Stabilize types in `AugmentedLagrangianMethodState`

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#242]
Currently `AugmentedLagrangianMethodState` has almost all of its fields abstractly typed. This can hurt performance. Can we get most (or all of them) concretely typed? I can make a PR that adds a few new type parameters for necessary types.

**Comment by mateuszbaran** [comment]
`ExactPenaltyMethodState` has a similar issue.

**Comment by kellertuer** [comment]
Oh that might have slipped my attention, sure we should do that.
