### ISSUE TITLE
PPA on Stiefel

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#252]
I've found an interesting paper about a modified version of PPA on Stiefel: https://optimization-online.org/2021/05/8401/ . Maybe we could add it to Manopt?

**Comment by mateuszbaran** [comment]
There is also this: https://arxiv.org/abs/1811.00980

**Comment by kellertuer** [comment]
PPA (Proximal Point Algorithm) is straightforward, mainly taking the state from gradient descent, removing step size adding a lambda_k, taking a prox objective there you go.

ProxGrad, especially the form from their paper – uff. Their subproblem (4.3) might be challenging for example and with a subsolver that would be some work at least.
