### ISSUE TITLE
quasi_Newton has issue with negative memory size.

### ISSUE THREAD

**Issue by salbert83** [JuliaManifolds/Manopt.jl#340]
The attached notebook fails when I set memory_size to -1.  I am running Julia 1.9.4 with the following package versions:

IJulia v1.24.2
ManifoldDiff v0.3.10
Manifolds v0.9.11
Manopt v0.4.45
Zygote v0.6.68

I had to save the notebook as a .txt file so Github would allow me to attach.

[QuasiNewtonQuestion.txt](https://github.com/JuliaManifolds/Manopt.jl/files/13802636/QuasiNewtonQuestion.txt)

**Comment by kellertuer** [comment]
Hi,
I can try to run that, but it would be easier if you could narrow it down to a minimal example with just a few lines of code that you could post here? 
That makes it easier to pin point the problem (also because I do not use Jupyter much and have to install it first now).

**Comment by mateuszbaran** [comment]
If you have the formula for real coordinate basis of tangent spaces to the complex sphere, I can add it to Manifolds.jl. That shouldn't be too hard to derive, you can probably just start from the function written by Ronny and split `X` to real and imaginary parts.

**Comment by kellertuer** [comment]
Yes, probably adapting that and getting to a complex-basis-with-real-coefficients vector for complex abstract spheres would be the way to go. For now I just do not have a good idea how to compute that.

**Comment by mateuszbaran** [comment]
BTW, I'd suggest trying L-BFGS with limited memory on Manopt 0.4.46 (will be released very soon), with Hager-Zhang linesearch from LineSearches.jl. After fixes it has similar performance to Optim.jl on a couple of test problems.

**Comment by kellertuer** [comment]
Note that the L here means `memory_size > 0`. A negative number would also do (inverse) BFGS as well, but storing a full matrix.
But yeah we are currently working on even getting these algorithms faster (ok, the “we” is definitely mainly Mateusz).

**Comment by kellertuer** [comment]
I started a first sketch, but I have to still figure out the details, mainly in allocation (along the way=) of the actual coefficient vector. If you have a nicer formula, feel free to contribute.

And – thanks – this was a nice thing to ponder about during my hike today, and also just about 30 minutes to heck this sketch.
I'll leave this open though we now have a place over on Manifolds.jl for this, in case there is general feedback on the current comments here.

**Comment by salbert83** [comment]
> BTW, I'd suggest trying L-BFGS with limited memory on Manopt 0.4.46 (will be released very soon), with Hager-Zhang linesearch from LineSearches.jl. After fixes it has similar performance to Optim.jl on a couple of test problems.

Yes, it does work quite well.  I just raised the issue because, based on the documentation, I wasn't expecting a crash.  Thanks to everyone for addressing so quickly and thoughtfully!

**Comment by kellertuer** [comment]
Well, usually one should not expect things to crash ;)

But we did start a section with each solver called “Technical Details” that lists which functions one should implement for a manifold for this solver to work.
This is meant for example when you implement your own manifold, that you know the minimal requirements. In your case it could also have helped to see “ah for the matrix variants I need a basis”. I will check whether that is in there and correctly phrased then.

Concerning the open PR on doing the basis you are missing – there are a few minor technical difficulties still, so it might take a while until that is covered, we are but only a very small team working on these packages involved here (originally 3, currently more realistically 2).

**Comment by kellertuer** [comment]
I will close this for now. My idea to compute an ONB for your case was not successful, so to be honest I just have no clue how to provide a good ONB in your case for the manifold you have.

I checked the docs and under Technical Derails (as mentioned in my last post) the `get_coordinates` requirement is mentioned as the last point https://manoptjl.org/stable/solvers/quasi_Newton/#sec-qn-technical-details. This function is exactly what a complex sphere (any of them, also the array spherre) are missing, but that is an issue for [Manifolds.jl](https://github.com/JuliaManifolds/Manifolds.jl/issues) and not here. 

If you feel the docs could be improved, feel free to comment on this issue and reopening it.
