### ISSUE TITLE
check_Hessian: retraction_method is not passed to gradient check

### ISSUE THREAD

**Issue by rs1909** [JuliaManifolds/Manopt.jl#342]
I believe that `retraction_method` keyword parameter is not passed onto the `check_gradient` call within `check_Hessian`:

https://github.com/JuliaManifolds/Manopt.jl/blame/a24c869897c732b510c71fcc2d7693f819e925d1/src/helpers/checks.jl#L297

Calling `check_gradient` directly does work with the same retraction, while `check_Hessian` fails.

**Comment by kellertuer** [comment]
Oh, well spotted :) Thanks for opening this issue, we must have missed that.

Do you want to open an PR? Otherwise I could do that later today (in Central Europe Time than is)

**Comment by rs1909** [comment]
Many thanks. Sorry I'd prefer not to create a PR, as I have never done
that. It is not urgent either, I've just switched off gradient checking and
done it separately, which works well.

**Comment by kellertuer** [comment]
No problem, I will do it later today then.

Since you re running it separately, do you think we missed any other keyword?

**Comment by kellertuer** [comment]
As you can see I just did the pull request. Later today, when all tests have passed I will merge it and register a new version, so probably tomorrow morning you will have Manopt.jl 0.4.47 where the bug is fixed.

Thanks again for reporting this.
