### ISSUE TITLE
Try DocumenterInterLinks.jl

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manopt.jl#364]
This package https://github.com/JuliaDocs/DocumenterInterLinks.jl looks amazing. We would need that ManifoldsBase.jl has generated once Documenter docs based on the 1.3, but then this should be a real great opportunity to improve the docs.

Once this works here, we can update a lot of links in our Org in general.

**Comment by mateuszbaran** [comment]
That would be great :+1:

**Comment by kellertuer** [comment]
I will try that as soon as I find out how to get the ManifoldsBase cos to once be generated with Documenter 1.3 (hopefully without tagging a new version).

**Comment by mateuszbaran** [comment]
Docs are regenerated when you make a special tag: https://documenter.juliadocs.org/stable/man/hosting/#Fixing-broken-release-deployments .
