### ISSUE TITLE
Purpose of dependency TestImages

### ISSUE THREAD

**Issue by Nikdwal** [JuliaManifolds/Manopt.jl#37]
Hello all,

I am developing a Julia package which does manifold optimisation, but now that I try it out on an older version of Julia (v 1.1.0) it seems that the dependency Manopt.jl cannot be resolved, because it requires a version of TestImages.jl that is too recent for Julia 1.1.0. Hence, my package could not be built. I do not see any reason why Manopt requires TestImages, and I have removed the dependency from a local clone of Manopt on my own machine. Now everything seems to be working just fine. Isn't this dependency superfluous? It seems to cause more harm than good.

**Comment by kellertuer** [comment]
Hi NIck,
really nice to see that you are also working on manifold optimization. Is the package somewhere available?

There is no real reason anymore. I once added it for some examples, but for sure (looking at that from today) the examples could mention that / take care of that themselves. I will remove that in the next release soon.

**Comment by Nikdwal** [comment]
Thanks! I will make the code available after the results are published. It is related to methods such as this one: https://arxiv.org/abs/1709.00033

**Comment by kellertuer** [comment]
Note that the dependency on the three color packages is necessary, since they are used in the exports to asymptote. And yes, if all of these are instead covered by PlottingReciepes, we can also remove those.

**Comment by kellertuer** [comment]
You should be good to go in an hour or so, once the TagBot has worked.

And nice area; so you are working with NIck I suppose? Very cool. Send him my regards.
