### ISSUE TITLE
typos

### ISSUE THREAD

**Issue by spaette** [JuliaManifolds/Manopt.jl#397]
Was `dictionary's` the intention here?

```
$ sed -n '793p' Manopt.jl/src/plans/record.jl
is called for the `Vector` and the result is added to the debug dictionaries entry
$ sed -n '1078p' Manopt.jl/src/plans/debug.jl
is called for the `Vector` and the result is added to the debug dictonaries entry
$
```

Florida
Intelligence
Variant
address
algorithm
criterion
deactivate
documentation
evaluation
generations
generations
otherwise
otherwise
symbol
than
wrapped

```
$ grep -n Flordia Manopt.jl/docs/src/references.bib
472:    SCHOOL    = {Flordia State University},
$ grep -n INtelligence Manopt.jl/docs/src/references.bib
220:    BOOKTITLE = {7th International Conference on Swarm INtelligence}
$ grep -nr Varant Manopt.jl
Manopt.jl/src/solvers/difference-of-convex-proximal-point.jl:434:    Varant I: allocating closed form of the prox
Manopt.jl/src/solvers/difference-of-convex-proximal-point.jl:453:    Varant II: in-place closed form of the prox
Manopt.jl/src/solvers/difference-of-convex-proximal-point.jl:471:    Varant III: subsolver variant of the prox
$ grep -n adress Manopt.jl/.vale.ini
47:Google.We = false # For tutorials we want to adress the user directly.
$ grep -nr "start of the algorith" Manopt.jl/tutorials/HowToDebug.qmd
79:* `:Start` to print something at the start of the algorith. At this place all other (the following) places are “reset”, by triggering each of them with an iteration number `0`
$ grep -n crtierion Manopt.jl/tutorials/ImplementOwnManifold.qmd
186:    stopping_criterion = StopAfterIteration(10),  # A simple stopping crtierion
$ grep -n dactivate Manopt.jl/tutorials/ImplementOwnManifold.qmd
50:# to keep the output and usage simple let's dactivate tutorial mode here
$ grep -n documenation Manopt.jl/docs/make.jl
10:Render the `Manopt.jl` documenation with optional arguments
$ grep -nr evalutation Manopt.jl
Manopt.jl/docs/src/tutorials/GeodesicRegression.md:157:`evalutation` type accordingly.
Manopt.jl/tutorials/GeodesicRegression.qmd:191:`evalutation` type accordingly.
$ grep -n generatiosn Manopt.jl/src/solvers/cma_es.jl
623:        return "At iteration $(c.at_iteration): for the last $(c.iterations_since_change) generatiosn the best objective value in each generation was equal to $(c.best_objective_at_last_change).\n"
$ grep -n gnerations Manopt.jl/src/solvers/cma_es.jl
883:        return "Range of best objective function values in the last $(length(c.best_value_history)) gnerations and all values in the current generation is below $(c.tol)\n"
$ grep -nr otherise Manopt.jl
Manopt.jl/test/plans/test_embedded.jl:94:        # otherise different
Manopt.jl/test/plans/test_cache.jl:285:        # otherise different
Manopt.jl/test/plans/test_cache.jl:334:        # otherise different
Manopt.jl/test/plans/test_counts.jl:74:        # otherise different
$ grep -n otherweise Manopt.jl/src/solvers/truncated_conjugate_gradient_descent.jl
747:    # otherweise accept step
$ grep -n symbold Manopt.jl/src/plans/debug.jl
1079:with said symbold. This is wrapped into the [`DebugWhenActive`](@ref),
$ grep -n thatn Manopt.jl/tutorials/HowToDebug.qmd
104:This also illustrates, that instead of `Symbol`s we can also always pass down a [`DebugAction`](@ref) directly, for example when there is a reason to create or configure the action more individually thatn the default from the symbol.
$ grep -n wrappedn Manopt.jl/src/plans/debug.jl
1163:If `:WhenActive` is present, the resulting Action is wrappedn in [`DebugWhenActive`](@ref),
$ 
```

WON'T FIX (typo in article title)

```
$ grep -n fuctions Manopt.jl/docs/src/references.bib
690:    TITLE     = {A proximal point algorithm for DC fuctions on Hadamard manifolds},
$
```

**Comment by kellertuer** [comment]
Nice, feel free to open a PR here as we :)

**Comment by spaette** [comment]
I can open a pull and mark it a draft.

> Was dictionary's the intention here?

`https://doi.org/10.1007/s10898-015-0282-7`

Have you an opinion on likelihood of @prcastro being one of the coauthors of that article?

The typo `fuctions` appears in the article title on the page which the above URL redirects to.

**Comment by kellertuer** [comment]
> I can open a pull and mark it a draft.
> 
> > Was dictionary's the intention here?

Sorry these comments are so super short that I have no clue what you mean with this question. Can you expand on that?

> 
> `https://doi.org/10.1007/s10898-015-0282-7`
> 
> Have you an opinion on likelihood of @prcastro being one of the coauthors of that article?

Who are you referring to? the @ does not link to anyone, so I am not sure whom ou are referring to or what that would mean / imply?
 
> The typo `fuctions` appears in the article title on the page which the above URL redirects to.

Oh! Then we should maybe keep that, I thought maybe I made that typo (though I usually use some tools to get bib info from the DOI). Interesting.

**Comment by spaette** [comment]
> expand on that

see the top of this ticket

```
$ sed -n '793p' Manopt.jl/src/plans/record.jl
is called for the `Vector` and the result is added to the debug dictionaries entry
$ sed -n '1078p' Manopt.jl/src/plans/debug.jl
is called for the `Vector` and the result is added to the debug dictonaries entry
$ 
```

**Comment by spaette** [comment]
Leaving any changes to the .bib file to another ticket/pull.

**Comment by kellertuer** [comment]
> > expand on that
> 
> see the top of this ticket
> 
> ```
> $ sed -n '793p' Manopt.jl/src/plans/record.jl
> is called for the `Vector` and the result is added to the debug dictionaries entry
> $ sed -n '1078p' Manopt.jl/src/plans/debug.jl
> is called for the `Vector` and the result is added to the debug dictonaries entry
> $ 
> ```

I saw that, but I have no clue what that means, sorry. I neither use sed (nor do I know what it does) nor do I know what the magic `-n ` means. hence the question for explanations for mere mortals

>  > @ does not link
> 
> that was the intention
> 
> it was unknown if that user was a coauthor; and might not therefore welcome receipt of a notification on this ticket

Oh, but quoting your text did then notify them, sorry for that, especially since that is not the author.

**Comment by spaette** [comment]
Was the intention singular, singular possessive, plural, or plural possessive?

dictionary, or if it possesses `entry,` then dictionary's

dictionaries, or if it possesses `entry`, then dictionaries'

Here are the respective file sections; as opposed to the GNU sed print outs of the specified lines.

src/plans/record.jl

```
For each `Pair` of a `Symbol` and a `Vector`, the [`RecordGroupFactory`](@ref)
is called for the `Vector` and the result is added to the debug dictionaries entry
with said symbol. This is wrapped into the [`RecordWhenActive`](@ref),
when the `:WhenActive` symbol is present
```

src/plans/debug.jl

in the below `dictonaries` is a typo

```
For each `Pair` of a `Symbol` and a `Vector`, the [`DebugGroupFactory`](@ref)
is called for the `Vector` and the result is added to the debug dictonaries entry
with said symbold. This is wrapped into the [`DebugWhenActive`](@ref),
when the `:WhenActive` symbol is present
```

**Comment by kellertuer** [comment]
Ah, I was missing all that context and was thinking it was some magic of the dictionary you are using or some dictionary sed is using or anything like that. I did not interpret your question as to actually referring to the word dictionary.

 Sure the second is a typo and what it in both cases should refer to is of course
`to the debug dictionaries‘  entry`, i.e. the entry of the dictionary.

**Comment by spaette** [comment]
entry of the dictionary

that would be `debug dictionary's entry`

entry of the dictionaries

that would be `debug dictionaries' entry`

for lack of thorough comprehension on my end please reiterate which you want

**Comment by kellertuer** [comment]
oh, then it is lack of English on my side, I meant the singular case, so my clarification has the  `´` in the wrong place. I can maybe put the fault on me having spent a week just filling forms and doing administrative work.

**Comment by spaette** [comment]
English
Ronny's code

Danish
Ronnys kode

Check if the ChangeLog.md entry is correct before merging.

**Comment by spaette** [comment]
Any work on the .bib file is left to someone else.
