### ISSUE TITLE
Refine storage of subsolver states

### ISSUE THREAD

**Issue by kellertuer** [JuliaManifolds/Manopt.jl#403]
See https://github.com/JuliaManifolds/Manopt.jl/pull/399#discussion_r1697275689,
we could store the evaluation mode of a closed form solution also in a small state to make the type of `sub_state` more unified.
The keyword should still accept just the evaluation type.

This sounds like an easy refactor task.

**Comment by mateuszbaran** [comment]
By the way, do you have an example of where a closed-form subsolver is used?

**Comment by kellertuer** [comment]
Frank-Wolfe often, Difference-of-Convex, maybe ALM sometimes?

In general it might also be nice to pass a “closed form solution” function to use some other packages solver as a subsolver.
