### ISSUE TITLE
Allocation of temporaries

### ISSUE THREAD

**Issue by mateuszbaran** [JuliaManifolds/Manopt.jl#72]
When allocating temporaries, like here: https://github.com/JuliaManifolds/Manopt.jl/blob/45f587c988bad525ca23d19110f9af38baf240ae/src/solvers/conjugate_gradient_descent.jl#L57 , `deepcopy` is not a good solution because for static arrays it will return a new static arrays, while if you want to override that temporary in-place (for example using mutating functions like `retract!`) you need a mutable value. To solve this you need to call `allocate` instead and then `copyto!` if you need the temporary to be initialized.

**Comment by kellertuer** [comment]
Thanks for the explanation.
So I should mimic, what we for example do in `exp` before calling `exp!`?

I can do that, I would just have to change this line for every solver then, that's why I ask first.

**Comment by mateuszbaran** [comment]
Yes, allocation in `exp` is a good example. That needs to be done for every variable you want to mutate using our mutating functions like `log!` or `exp!`, or if you want broadcast assignment (`Y .= X1 .+ X2`).

**Comment by kellertuer** [comment]
cool. I will adapt the non-mutating solver functions tomorrow, then.

**Comment by kellertuer** [comment]
Hm. What do I do with some nested power points? There `allocate` (at least just `allocate(x)`) `copyto!` to something different than `deepcopy`?

**Comment by mateuszbaran** [comment]
Hm, I work so rarely with nested power points that I didn't see that coming. We can either modify the nested power manifold to replace the arrays inside instead of overwriting them or make a `deepcopyto!` and use it in any place where the nested power manifold could appear.

**Comment by kellertuer** [comment]
Ah, I could also really use `allocate_result(M, f, x)` which has a default for arbitrary f right?

**Comment by mateuszbaran** [comment]
Yes but that doesn't solve the `copyto!` issue. Right now `copyto!` can't be safely used with nested power manifolds.

**Comment by kellertuer** [comment]
Ah. Hm. So this is more complicated than I thought.

**Comment by mateuszbaran** [comment]
My initial thinking is that we should modify the nested power manifold so that it doesn't do this nested overriding but I can't tell for sure that it's the right thing until I actually do it.

**Comment by kellertuer** [comment]
I would not know how to do this, but if you see how that would help, sure.
I would*ve tried to do a `allocate`-style variant of `copyto!` that works recursively.
